FROM docker.io/library/postgres:18.6-bookworm@sha256:1c59e2c3c818eaa0f0628f695b36e7c9e362d6b219b36a54a32df645cbd7e1af
COPY deploy/pg-start.sh /usr/local/bin/delivery-pg-start
COPY deploy/pg-init.sh /docker-entrypoint-initdb.d/10-delivery.sh
RUN chmod 0555 /usr/local/bin/delivery-pg-start /docker-entrypoint-initdb.d/10-delivery.sh
USER 1001
ENTRYPOINT ["/usr/local/bin/delivery-pg-start"]
