apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: secure-delivery
resources:
  - namespace.yaml
  - config.yaml
  - app.yaml
  - postgres.yaml
  - network.yaml
  - backup.yaml
configMapGenerator:
  - name: delivery-backup-script
    files: [backup.sh]
generatorOptions:
  disableNameSuffixHash: true
